%% PLOS_Reviewer_Sims.m
%  ═══════════════════════════════════════════════════════════════════════
%  NEW SIMULATIONS for PLOS ONE Revision (PONE-D-26-19361)
%  Run AFTER Tdoa_full_run.m (loads full_run_results.mat)
%
%  Part P1: 100-MC re-run of 8x3 head-to-head       (R2 Major 2.8)
%           -> mean ± std (3 decimals) + bootstrap 95% CI on key gains
%  Part P2: Single-tag lever-arm diagnostic          (R2 Major 2.3)
%           -> origin-frame vs tag-point position RMSE
%  Part P3: GSO visibility robustness                (R2 Major 2.6)
%           -> elevation slew ±1.5 deg over docking window
%  Part P4: UWB update-rate sweep + rough sea        (R1 Q4)
%           -> proposed method at 1/2/5/10/20 Hz UWB, Hs = 1.5 & 3.0 m
%  Part P5: Tag-geometry CRLB sensitivity            (R1 Q6)
%           -> 2-D sweep: height spread x lateral offset
%  Part P6: Degenerate anchor geometries             (R1 Q7)
%  Part P7: EKF computational profiling              (R1 Q8)
%
%  All functions below are verbatim copies from Tdoa_full_run.m so that
%  results are generated by the SAME codebase as the paper.
%  ═══════════════════════════════════════════════════════════════════════
clear; clc; close all;
rng(42);
fprintf('╔═══════════════════════════════════════════════════════╗\n');
fprintf('║  PLOS ONE REVISION — New Simulations                  ║\n');
fprintf('╚═══════════════════════════════════════════════════════╝\n\n');

if ~exist('full_run_results.mat','file')
    error('Run Tdoa_full_run.m first to generate full_run_results.mat');
end
load('full_run_results.mat');
fprintf('  ✓ Loaded full_run_results.mat\n');

% Rebuild trajectory and platform (same rng state pattern as paper run)
waves = gen_waves(par);
traj  = gen_traj(par, waves);
plat  = gen_plat(par, waves);
burn  = round(2/par.dt);
fprintf('  ✓ Rebuilt trajectory and platform\n\n');

methods = {'gps_pos','gpsnav_pos','gps_4ant','gpsnav_4ant',...
           'uwb1tag_gps','mtag_only','mtag_gps','mtag_gpsnav'};
mnames  = {'GPS pos only','GPS+NavIC pos only',...
           '4-ant GPS att','4-ant GPS+NavIC att',...
           '1-tag UWB+GPS','Multi-tag UWB only',...
           'Multi-tag+GPS','Multi-tag+GPS+NavIC (proposed)'};
snames  = {'S1:Nominal','S2:Shadow','S3:Outage'};

%% ═══ PART P1: 100-MC RE-RUN (R2 Major 2.8) ═══════════════════════════
%  Increase Monte Carlo count from 30 to 100 and report statistics with
%  enough decimals that the ±std is never displayed as 0.00.
%  Uses parfor if Parallel Computing Toolbox is available.
fprintf('--- Part P1: 100-MC re-run of the 8-method head-to-head ---\n');
NMC2 = 100;                    % set to 500 for the final table if time allows
use_par = license('test','Distrib_Computing_Toolbox') && ~isempty(ver('parallel'));
fprintf('  NMC = %d  (parfor: %d)\n', NMC2, use_par);

res2_pos   = zeros(8,3,NMC2);
res2_hdg   = zeros(8,3,NMC2);
res2_roll  = zeros(8,3,NMC2);
res2_pitch = zeros(8,3,NMC2);

tic_P1 = tic;
for si = 1:3
    fprintf('  Scenario %d:\n', si);
    tmp = zeros(8,4,NMC2);       % slice-friendly container for parfor
    if use_par
        parfor mc = 1:NMC2
            tmp(:,:,mc) = one_mc(traj, plat, par, si, sat_gps, sat_navic, ...
                                 methods, mc, burn);
        end
    else
        for mc = 1:NMC2
            if mod(mc,10)==0; fprintf('    MC %d/%d\n', mc, NMC2); end
            tmp(:,:,mc) = one_mc(traj, plat, par, si, sat_gps, sat_navic, ...
                                 methods, mc, burn);
        end
    end
    res2_pos(:,si,:)   = tmp(:,1,:);
    res2_hdg(:,si,:)   = tmp(:,2,:);
    res2_roll(:,si,:)  = tmp(:,3,:);
    res2_pitch(:,si,:) = tmp(:,4,:);
end
fprintf('  Part P1 runtime: %.1f min\n\n', toc(tic_P1)/60);

% ---- Table with 3-decimal std (fixes the "±0.00" issue) ----
fprintf('  POSITION RMSE (m) and HEADING RMSE (deg), %d MC:\n', NMC2);
for mi = 1:8
    fprintf('  %-30s', mnames{mi});
    for si = 1:3
        fprintf('| %7.2f±%.3f  %7.3f±%.3f ', ...
            mean(res2_pos(mi,si,:)), std(res2_pos(mi,si,:)), ...
            mean(res2_hdg(mi,si,:)), std(res2_hdg(mi,si,:)));
    end
    fprintf('\n');
end
fprintf('\n  ROLL / PITCH RMSE (deg), multi-tag methods:\n');
for mi = [6 7 8]
    fprintf('  %-30s', mnames{mi});
    for si = 1:3
        fprintf('| R %5.3f±%.3f  P %5.3f±%.3f ', ...
            mean(res2_roll(mi,si,:)),  std(res2_roll(mi,si,:)), ...
            mean(res2_pitch(mi,si,:)), std(res2_pitch(mi,si,:)));
    end
    fprintf('\n');
end

% ---- Bootstrap 95% CI on the two headline gains ----
nboot = 10000;
h_mtgps  = squeeze(res2_hdg(7,1,:));   % Multi-tag+GPS, S1
h_prop   = squeeze(res2_hdg(8,1,:));   % Proposed, S1
p_1tag   = squeeze(res2_pos(5,2,:));   % 1-tag UWB+GPS, S2
p_prop2  = squeeze(res2_pos(8,2,:));   % Proposed, S2
g_hdg = zeros(nboot,1); g_pos = zeros(nboot,1);
for b = 1:nboot
    ii = randi(NMC2,NMC2,1);
    g_hdg(b) = (mean(h_mtgps(ii)) - mean(h_prop(ii))) / mean(h_mtgps(ii)) * 100;
    g_pos(b) = (mean(p_1tag(ii))  - mean(p_prop2(ii))) / mean(p_1tag(ii)) * 100;
end
fprintf('\n  NavIC heading gain (S1): %.1f%%  [95%% CI: %.1f – %.1f]\n', ...
    mean(g_hdg), prctile(g_hdg,2.5), prctile(g_hdg,97.5));
fprintf('  Position gain vs 1-tag (S2): %.1f%%  [95%% CI: %.1f – %.1f]\n\n', ...
    mean(g_pos), prctile(g_pos,2.5), prctile(g_pos,97.5));

%% ═══ PART P2: SINGLE-TAG LEVER-ARM DIAGNOSTIC (R2 Major 2.3) ═════════
%  Show that the 38 m "position RMSE" of 1-tag UWB+GPS is the BODY-ORIGIN
%  error produced by the Theorem-1 rotation–translation ambiguity acting
%  on the 40 m tag lever arm — the tag-point itself is estimated well.
fprintf('--- Part P2: single-tag lever-arm diagnostic ---\n');
NMC_p2 = 30; b1 = par.tags_body(1,:)';
org_rmse = zeros(1,NMC_p2); tag_rmse = zeros(1,NMC_p2); hdg_rms = zeros(1,NMC_p2);
for mc = 1:NMC_p2
    rng(mc*1000+1);   % same seeds as paper S1 runs
    mm = gen_meas(traj, plat, par, 1, sat_gps, sat_navic, 'gps_only');
    [est,~] = run_ekf(traj, plat, mm, par, 'uwb1tag_gps', 'perfect');
    idx = burn+1:par.N;
    ep = traj.pos(:,idx) - est.pos(:,idx);
    org_rmse(mc) = sqrt(mean(sum(ep.^2,1)));
    % tag-point error: p_tag = R b1 + t for both truth and estimate
    ep_t = zeros(3,numel(idx)); c = 0;
    for k = idx
        c = c+1;
        Rt = eul2r(traj.att(1,k),traj.att(2,k),traj.att(3,k));
        Re = eul2r(est.att(1,k), est.att(2,k), est.att(3,k));
        ep_t(:,c) = (Rt*b1+traj.pos(:,k)) - (Re*b1+est.pos(:,k));
    end
    tag_rmse(mc) = sqrt(mean(sum(ep_t.^2,1)));
    eh = wrapToPi(traj.att(1,idx) - est.att(1,idx));
    hdg_rms(mc) = rad2deg(sqrt(mean(eh.^2)));
end
Lh = norm(b1(1:2));
fprintf('  Body-origin position RMSE : %.2f ± %.2f m\n', mean(org_rmse), std(org_rmse));
fprintf('  TAG-POINT position RMSE   : %.2f ± %.2f m   <-- well below origin error\n', ...
    mean(tag_rmse), std(tag_rmse));
fprintf('  Heading RMSE              : %.1f deg\n', mean(hdg_rms));
fprintf('  Lever-arm prediction 2·%.0f·sin(hdg/2) = %.1f m (matches origin error)\n\n', ...
    Lh, 2*Lh*sin(deg2rad(mean(hdg_rms))/2));

%% ═══ PART P3: GSO VISIBILITY ROBUSTNESS (R2 Major 2.6) ═══════════════
%  Real-data LOS drift (Kaggle): GEO PRNs 3/6/7 ≤0.7°/hr; GSO PRNs 2/4/5
%  ≤8.5°/hr  =>  ≤ ±1.5° elevation change over a 10-min docking window.
%  Test: slew all NavIC elevations by ±1.5° linearly over the run and
%  verify heading RMSE of the proposed method is unaffected.
fprintf('--- Part P3: GSO elevation-slew robustness ---\n');
NMC_p3 = 20; slews = [-1.5 0 +1.5];
hdg_slew = zeros(numel(slews), NMC_p3);
for si_slew = 1:numel(slews)
    sat_navic_sl = sat_navic; sat_navic_sl(:,2) = sat_navic(:,2) + slews(si_slew);
    for mc = 1:NMC_p3
        rng(mc*1000+2);   % S2 (shadow) — the stressing scenario
        mm = gen_meas(traj, plat, par, 2, sat_gps, sat_navic_sl, 'gps_navic');
        [est,~] = run_ekf(traj, plat, mm, par, 'mtag_gpsnav', 'perfect');
        eh = wrapToPi(traj.att(1,burn+1:end) - est.att(1,burn+1:end));
        hdg_slew(si_slew,mc) = rad2deg(sqrt(mean(eh.^2)));
    end
    fprintf('  Elevation slew %+0.1f deg: heading RMSE %.3f ± %.3f deg\n', ...
        slews(si_slew), mean(hdg_slew(si_slew,:)), std(hdg_slew(si_slew,:)));
end
fprintf('\n');

%% ═══ PART P4: UWB UPDATE-RATE SWEEP + ROUGH SEA (R1 Q4) ══════════════
%  Sub-sample the 20 Hz UWB stream to 10/5/2/1 Hz and evaluate the
%  proposed method under Hs = 1.5 m and Hs = 3.0 m.
fprintf('--- Part P4: UWB rate sweep under wave dynamics ---\n');
rates = [20 10 5 2 1]; NMC_p4 = 20;
for hs_case = [1.5 3.0]
    par4 = par; par4.Hs = hs_case;
    waves4 = gen_waves(par4); traj4 = gen_traj(par4, waves4); plat4 = gen_plat(par4, waves4);
    fprintf('  Hs = %.1f m:\n', hs_case);
    for ri = 1:numel(rates)
        keep = round(1/(rates(ri)*par.dt));      % keep every k-th UWB epoch
        hh = zeros(1,NMC_p4); pp = zeros(1,NMC_p4); rr = zeros(1,NMC_p4); pt = zeros(1,NMC_p4);
        for mc = 1:NMC_p4
            rng(mc*1000+1);
            mm = gen_meas(traj4, plat4, par4, 1, sat_gps, sat_navic, 'gps_navic');
            for k = 1:par4.N
                if mod(k-1,keep) ~= 0; mm.uwb(k).valid = false; end
            end
            [est,~] = run_ekf(traj4, plat4, mm, par4, 'mtag_gpsnav', 'perfect');
            idx = burn+1:par4.N;
            ep = traj4.pos(:,idx) - est.pos(:,idx);
            pp(mc) = sqrt(mean(sum(ep.^2,1)));
            eh = wrapToPi(traj4.att(1,idx) - est.att(1,idx)); hh(mc) = rad2deg(sqrt(mean(eh.^2)));
            er = wrapToPi(traj4.att(2,idx) - est.att(2,idx)); rr(mc) = rad2deg(sqrt(mean(er.^2)));
            e2 = wrapToPi(traj4.att(3,idx) - est.att(3,idx)); pt(mc) = rad2deg(sqrt(mean(e2.^2)));
        end
        fprintf('    UWB %2d Hz: pos %.2f m | hdg %.3f | roll %.3f | pitch %.3f deg\n', ...
            rates(ri), mean(pp), mean(hh), mean(rr), mean(pt));
    end
end
fprintf('\n');

%% ═══ PART P5: TAG-GEOMETRY CRLB SENSITIVITY (R1 Q6) ══════════════════
fprintf('--- Part P5: tag geometry sensitivity (CRLB) ---\n');
p_ref = [100;0;0]; att_ref = [pi 0 0];
hspread = 0:1:12; woff = 0:2.5:25;
crlb_h = zeros(numel(hspread), numel(woff), 3);   % hdg, roll, pitch
for hi = 1:numel(hspread)
    for wi = 1:numel(woff)
        h = hspread(hi); w = woff(wi);
        tg = [40 0 8; -40 0 8-h/2; 0 -w 8+h/2];
        [~,~,~,Call] = crlb_full(p_ref, att_ref, tg, par);
        crlb_h(hi,wi,:) = Call;
    end
end
figure('Position',[100 100 1200 350]);
lbl = {'Heading CRLB (deg)','Pitch CRLB (deg)','Roll CRLB (deg)'};  
for a = 1:3
    subplot(1,3,a); imagesc(woff, hspread, squeeze(crlb_h(:,:,a)));
    set(gca,'YDir','normal'); colorbar; xlabel('Lateral offset w (m)');
    ylabel('Height spread h (m)'); title(lbl{a});
end
saveas(gcf,'fig_R1Q6_tag_geometry.png');
fprintf('  Saved fig_R1Q6_tag_geometry.png\n\n');

%% ═══ PART P6: DEGENERATE ANCHOR GEOMETRIES (R1 Q7) ═══════════════════
fprintf('--- Part P6: degenerate anchor geometries ---\n');
anch_cases = {par.anch_body, ...
    [0 0 5; 80 0 5; -80 0 5; 0 25 5], ...          % 4 coplanar
    [0 0 5; 80 0 5; -80 0 5; 40 12.5 35], ...      % 4 non-coplanar (min)
    [0 0 5; 40 0 5; 80 0 5; -80 0 5]};             % 4 collinear
anch_names = {'paper 6-anchor','4 coplanar (z=5)','4 non-coplanar (min)','4 collinear'};
for c = 1:4
    parc = par; parc.anch_body = anch_cases{c}; parc.M = size(anch_cases{c},1); parc.ref = 1;
    [cp, ch, rk] = compute_crlb_6dof(p_ref, att_ref, par.tags_body, parc);
    fprintf('  %-22s rank %d | CRLB pos %8.2f m | hdg %8.2f deg\n', anch_names{c}, rk, cp, ch);
end
fprintf(['  NOTE for response: coplanar anchors keep local FIM rank 6 but create a\n' ...
         '  discrete MIRROR ambiguity across the anchor plane (global unobservability);\n' ...
         '  collinear anchors are locally singular (continuous rotational ambiguity).\n\n']);

%% ═══ PART P7: EKF COMPUTATIONAL PROFILING (R1 Q8) ════════════════════
fprintf('--- Part P7: EKF computational profiling ---\n');
mm = gen_meas(traj, plat, par, 1, sat_gps, sat_navic, 'gps_navic');
tic_p7 = tic;
[est,~] = run_ekf(traj, plat, mm, par, 'mtag_gpsnav', 'perfect');
t_run = toc(tic_p7);
fprintf('  Full 300 s run (%d epochs): %.2f s wall time in MATLAB\n', par.N, t_run);
fprintf('  => %.0f us per 50 ms epoch (%.2f%% of real-time budget)\n\n', ...
    t_run/par.N*1e6, t_run/par.N/par.dt*100);

%% ═══ SAVE ═══
save('plos_revision_results.mat', 'res2_pos','res2_hdg','res2_roll','res2_pitch', ...
     'org_rmse','tag_rmse','hdg_rms','hdg_slew','crlb_h','hspread','woff','NMC2');
fprintf('✓ All results saved to plos_revision_results.mat\n');

%% ═══ LOCAL HELPERS (new) ═════════════════════════════════════════════
function out = one_mc(traj, plat, par, si, sat_gps, sat_navic, methods, mc, burn)
    out = zeros(8,4);
    rng(mc*1000+si);
    for mi = 1:8
        if any(mi==[2 4 8]); gnss_mode='gps_navic'; else; gnss_mode='gps_only'; end
        mm = gen_meas(traj, plat, par, si, sat_gps, sat_navic, gnss_mode);
        [est,~] = run_ekf(traj, plat, mm, par, methods{mi}, 'perfect');
        ep = traj.pos(:,burn+1:end) - est.pos(:,burn+1:end);
        out(mi,1) = sqrt(mean(sum(ep.^2,1)));
        eh = wrapToPi(traj.att(1,burn+1:end) - est.att(1,burn+1:end));
        out(mi,2) = rad2deg(sqrt(mean(eh.^2)));
        er = wrapToPi(traj.att(2,burn+1:end) - est.att(2,burn+1:end));
        out(mi,3) = rad2deg(sqrt(mean(er.^2)));
        ept = wrapToPi(traj.att(3,burn+1:end) - est.att(3,burn+1:end));
        out(mi,4) = rad2deg(sqrt(mean(ept.^2)));
    end
end

function [cp, ch, rk, Call] = crlb_full(p, att, tags, par)
    % same as compute_crlb_6dof but returns per-axis attitude CRLB
    M = par.M; ref = par.ref; all_J = [];
    a = par.anch_body + par.plat_pos';
    for ti = 1:size(tags,1)
        R_s = eul2r(att(1),att(2),att(3)); tw = R_s*tags(ti,:)' + p;
        r0 = norm(tw - a(ref,:)');
        for j = 1:M
            if j == ref; continue; end
            rj = norm(tw - a(j,:)'); ej = (tw - a(j,:)')/max(rj,.01);
            e0 = (tw - a(ref,:)')/max(r0,.01); row = zeros(1,6); row(1:3) = (ej-e0)';
            for ai = 1:3
                ap = att; ap(ai) = ap(ai) + 1e-5;
                Rp = eul2r(ap(1),ap(2),ap(3)); twp = Rp*tags(ti,:)' + p;
                rjp = norm(twp - a(j,:)'); r0p = norm(twp - a(ref,:)');
                row(3+ai) = ((rjp - r0p) - (rj - r0))/1e-5;
            end
            all_J = [all_J; row];
        end
    end
    FIM = all_J'*(1/par.sig_tdoa^2*eye(size(all_J,1)))*all_J;
    rk = rank(FIM);
    if rk >= 6
        C = inv(FIM); cp = sqrt(trace(C(1:3,1:3))); ch = rad2deg(sqrt(C(4,4)));
        Call = rad2deg(sqrt([C(4,4) C(5,5) C(6,6)]));
    else
        cp = 999; ch = 999; Call = [999 999 999];
    end
end

%% ═══ FUNCTIONS COPIED VERBATIM FROM Tdoa_full_run.m ══════════════════
function s = tern(cond, a, b)
    if cond; s = a; else; s = b; end
end

function traj = gen_traj(par, waves)
    N=par.N; dt=par.dt; t=par.t;
    pos=zeros(3,N); vel=zeros(3,N); att=zeros(3,N);
    pos(:,1)=[500;50;0]; att(1,1)=pi;
    
    % Wave-induced ship motion using JONSWAP + ship RAOs
    % Physical scaling: ship responds MORE than dock (lighter, shorter)
    heave_rms = (par.Hs/4) * 0.9;                     % supply vessel heave ~90% of Hs/4
    roll_rms  = deg2rad((par.Hs / par.ship_B) * 30);   % ~30×(Hs/B) degrees — more than dock
    pitch_rms = deg2rad((par.Hs / par.ship_L) * 30);   % ~30×(Hs/L) degrees — more than dock
    surge_rms = par.Hs * 0.15;                          % surge perturbation
    sway_rms  = par.Hs * 0.10;                          % sway perturbation
    
    ship_hv = compute_rao_response(waves, par.ship_Tn_heave, par.ship_zeta_heave, heave_rms, t);
    ship_rl = compute_rao_response(waves, par.ship_Tn_roll, par.ship_zeta_roll, roll_rms, t);
    ship_pt = compute_rao_response(waves, par.ship_Tn_pitch, par.ship_zeta_pitch, pitch_rms, t);
    ship_sg = compute_rao_response(waves, par.ship_Tn_heave*1.3, 0.15, surge_rms, t);
    ship_sw = compute_rao_response(waves, par.ship_Tn_roll*0.8, 0.10, sway_rms, t);
    
    for k=2:N; tk=t(k);
        % Guidance: approach path toward dock
        if tk<60; th=atan2(-pos(2,k-1),-pos(1,k-1)); sp=4;
        elseif tk<120; th=atan2(-pos(2,k-1),-pos(1,k-1)); sp=max(2,4-(tk-60)/60*2);
        elseif tk<180; th=atan2(-pos(2,k-1),-pos(1,k-1)); sp=max(1,2-(tk-120)/60);
        elseif tk<240; fr=(tk-180)/60; th=pi+fr*(-pi/2); sp=max(.5,1-fr*.5);
        else; th=att(1,k-1); sp=.2; end
        dh=wrapToPi(th-att(1,k-1)); om=max(min(.3*dh,.05),-.05);
        
        % Heading = guidance + wave-induced yaw
        att(1,k)=wrapToPi(att(1,k-1)+om*dt);
        % Roll and pitch from wave spectrum (NOT simple sine anymore)
        att(2,k) = ship_rl(k);   % wave-induced roll
        att(3,k) = ship_pt(k);   % wave-induced pitch
        
        cs=norm(vel(1:2,k-1)); if cs<.01; cs=sp; end
        ns=cs+.1*(sp-cs)*dt;
        vel(1,k)=ns*cos(att(1,k)) + (ship_sg(min(k,N))-ship_sg(max(k-1,1)))/dt*0.1;
        vel(2,k)=ns*sin(att(1,k)) + (ship_sw(min(k,N))-ship_sw(max(k-1,1)))/dt*0.1;
        vel(3,k) = (ship_hv(min(k,N))-ship_hv(max(k-1,1)))/dt; % heave velocity
        pos(1,k) = pos(1,k-1) + vel(1,k)*dt;
        pos(2,k) = pos(2,k-1) + vel(2,k)*dt;
        pos(3,k) = ship_hv(k);  % heave displacement directly
    end
    traj.pos=pos; traj.vel=vel; traj.att=att;
    traj.ship_hv=ship_hv; traj.ship_rl=ship_rl; traj.ship_pt=ship_pt;
end

function plat = gen_plat(par, waves)
    t=par.t; N=par.N;
    
    % Dock 6-DOF response using RAOs
    % amp_scale = desired RMS amplitude (peak ≈ 2.5 × RMS for broadband)
    %
    % Physical scaling with Hs:
    %   Heave RMS ≈ (Hs/4) × heave_transfer  (heave_transfer ~0.5-0.8 for FPSO)
    %   Roll  RMS ≈ (Hs/B) × roll_factor      (rad, empirical)
    %   Pitch RMS ≈ (Hs/L) × pitch_factor     (rad, empirical)
    
    heave_rms = (par.Hs/4) * 0.6;                    % ~0.6 transfer for moored FPSO
    roll_rms  = deg2rad((par.Hs / par.dock_B) * 40);  % empirical: ~40×(Hs/B) degrees
    pitch_rms = deg2rad((par.Hs / par.dock_L) * 30);  % empirical: ~30×(Hs/L) degrees
    yaw_rms   = deg2rad(par.Hs * 0.3);                % slow yaw: ~0.3°/m of Hs
    surge_rms = par.dock_drift * par.Hs;               % mooring drift scales with Hs
    sway_rms  = par.dock_drift * par.Hs * 0.5;
    
    hv = compute_rao_response(waves, par.dock_Tn_heave, par.dock_zeta_heave, heave_rms, t);
    rl = compute_rao_response(waves, par.dock_Tn_roll, par.dock_zeta_roll, roll_rms, t);
    pt = compute_rao_response(waves, par.dock_Tn_pitch, par.dock_zeta_pitch, pitch_rms, t);
    yw = compute_rao_response(waves, 30, 0.2, yaw_rms, t);
    sg = compute_rao_response(waves, 45, 0.15, surge_rms, t);
    sw = compute_rao_response(waves, 55, 0.12, sway_rms, t);
    
    % Compute anchor world positions at each epoch
    aw=zeros(par.M,3,N); da=zeros(par.M,N);
    for k=1:N
        R=eul2r(yw(k),pt(k),rl(k));
        tr=par.plat_pos+[sg(k);sw(k);hv(k)];
        for j=1:par.M
            aw(j,:,k)=(R*par.anch_body(j,:)'+tr)';
            da(j,k)=norm(squeeze(aw(j,:,k))'-par.anch_body(j,:)'-par.plat_pos);
        end
    end
    plat.hv=hv; plat.rl=rl; plat.pt=pt; plat.yw=yw;
    plat.sg=sg; plat.sw=sw;
    plat.aw=aw; plat.dm=mean(da(:)); plat.dx=max(da(:));
end

function waves = gen_waves(par)
    % JONSWAP wave spectrum generation
    % Returns struct with frequencies, amplitudes, and random phases
    % Same phases used by both ship and dock (correlated sea)
    
    nw = par.n_waves;
    wp = 2*pi/par.Tp;  % peak frequency (rad/s)
    
    % Frequency range: 0.3*wp to 3*wp
    w = linspace(0.3*wp, 3*wp, nw);
    dw = w(2)-w(1);
    
    % JONSWAP spectrum: S(w) = α·g²/w⁵ · exp(-5/4·(wp/w)⁴) · γ^r
    % where r = exp(-(w-wp)²/(2·σ²·wp²))
    % σ = 0.07 for w≤wp, 0.09 for w>wp
    g = 9.81;
    alpha = 0.0081;  % Phillips constant (adjusted for Hs)
    
    S = zeros(1, nw);
    for i = 1:nw
        if w(i) <= wp; sigma = 0.07; else; sigma = 0.09; end
        r = exp(-(w(i)-wp)^2 / (2*sigma^2*wp^2));
        S(i) = alpha * g^2 / w(i)^5 * exp(-5/4*(wp/w(i))^4) * par.gamma_js^r;
    end
    
    % Scale spectrum to match desired Hs: Hs = 4·sqrt(m0)
    m0 = trapz(w, S);
    Hs_computed = 4*sqrt(m0);
    S = S * (par.Hs / Hs_computed)^2;
    
    % Wave amplitudes from spectrum
    a = sqrt(2 * S * dw);
    
    % Random phases (SHARED between ship and dock — same ocean!)
    ph = 2*pi*rand(1, nw);
    
    waves.w = w;
    waves.a = a;
    waves.ph = ph;
    waves.nw = nw;
    waves.Hs = par.Hs;
    waves.Tp = par.Tp;
end

function x = compute_rao_response(waves, Tn, zeta, amp_scale, t)
    % Compute vessel response to wave spectrum using simplified RAO
    % RAO(w) = 1 / sqrt((1-(w/wn)²)² + (2·ζ·w/wn)²)
    %
    % amp_scale = desired RMS amplitude of output signal
    % The RAO shapes the frequency content; output is then
    % normalized so that RMS(output) = amp_scale
    
    wn = 2*pi/Tn;  % natural frequency
    N = length(t);
    x = zeros(1, N);
    
    for i = 1:waves.nw
        w = waves.w(i);
        r = w/wn;
        rao_mag = 1 / sqrt((1 - r^2)^2 + (2*zeta*r)^2);
        rao_phase = atan2(-2*zeta*r, 1-r^2);
        x = x + waves.a(i) * rao_mag * sin(w*t + waves.ph(i) + rao_phase);
    end
    
    % Normalize: scale so that RMS = amp_scale
    x_rms = sqrt(mean(x.^2));
    if x_rms > 1e-10
        x = x * (amp_scale / x_rms);
    end
end

function R = eul2r(y,p,r)
    cy=cos(y);sy=sin(y);cp=cos(p);sp=sin(p);cr=cos(r);sr=sin(r);
    R=[cy*cp,cy*sp*sr-sy*cr,cy*sp*cr+sy*sr;sy*cp,sy*sp*sr+cy*cr,sy*sp*cr-cy*sr;-sp,cp*sr,cp*cr];
end

function [sat_gps, sat_navic] = gen_satellites(par)
    sat_gps = [30 45; 85 25; 140 60; 195 35; 230 50; 280 20; 320 40; 355 15];
    % NavIC: 3 GEO (high el) + 4 GSO — these are overridden if real data loaded
    sat_navic = [170 65; 225 70; 310 55; 145 45; 200 50; 260 40; 340 35];
end

function mask = compute_dock_mask(d, par)
    if d > 300; mask.az_block = 0; mask.el_block = 0;
    else
        mask.az_block = min(90, 45 + 45*(1-d/300));
        mask.el_block = min(40, 10 + 30*(1-d/300));
    end
    mask.dock_az = 0;
end

function [nvis, pdop_val] = count_visible(sats, mask, par)
    if isempty(sats); nvis=0; pdop_val=99; return; end
    vis = true(size(sats,1),1);
    for s = 1:size(sats,1)
        az = sats(s,1); el = sats(s,2);
        az_diff = abs(wrapTo180(az - mask.dock_az));
        if az_diff < mask.az_block && el < mask.el_block; vis(s) = false; end
        if el < 10; vis(s) = false; end
    end
    nvis = sum(vis);
    if nvis >= 4
        sv = sats(vis,:);
        H = zeros(nvis, 4);
        for s = 1:nvis
            az_r = deg2rad(sv(s,1)); el_r = deg2rad(sv(s,2));
            H(s,:) = [cos(el_r)*sin(az_r), cos(el_r)*cos(az_r), sin(el_r), 1];
        end
        G = inv(H'*H);
        pdop_val = sqrt(G(1,1)+G(2,2)+G(3,3));
    else; pdop_val = 99; end
end

function meas = gen_meas(traj, plat, par, scen, sat_gps, sat_navic, gnss_mode)
    N=par.N; dt=par.dt; M=par.M; ref=par.ref;
    gp=round(1/par.gnss_rate/dt);
    gnss(N)=struct('valid',false,'z',[],'R',[]);
    gnss_att(N)=struct('valid',false,'z',[],'R',[]);
    uwb(N)=struct('valid',false,'z_tags',{cell(1,par.Ntags)},'aidx_tags',{cell(1,par.Ntags)},'apos',[]);

    for k=1:N
        gnss(k).valid=false; gnss_att(k).valid=false;
        uwb(k).valid=false; uwb(k).z_tags=cell(1,par.Ntags); uwb(k).aidx_tags=cell(1,par.Ntags);

        if mod(k-1,gp)==0
            rp=norm(traj.pos(:,k)-par.plat_pos);
            sg=par.sig_gnss; out=false;
            if rp<par.gnss_shadow_rng
                if scen>=2; out=true; else; sg=sg*par.gnss_mp_infl; end
            elseif rp<par.gnss_mp_rng; sg=sg*par.gnss_mp_infl*(rp/par.gnss_mp_rng); end
            if scen==3 && par.t(k)>180; out=true; end
            if ~out
                R_ship=eul2r(traj.att(1,k),traj.att(2,k),traj.att(3,k));
                gw=R_ship*par.gnss_body+traj.pos(:,k);
                mask_k = compute_dock_mask(rp, par);
                if strcmp(gnss_mode,'gps_navic'); sats_k=[sat_gps;sat_navic];
                else; sats_k=sat_gps; end
                [ns_k, pdop_k] = count_visible(sats_k, mask_k, par);
                
                % Position noise scales with PDOP (more sats → better DOP → less noise)
                pdop_ref = 2.0;  % reference PDOP for sig_gnss
                sig_pos = sg * min(pdop_k/pdop_ref, 5.0);  % cap at 5× inflation
                
                gnss(k).valid=true; gnss(k).z=gw+sig_pos*randn(3,1); gnss(k).R=sig_pos^2*eye(3);
                if ns_k >= 5
                    mp = 1+5*exp(-rp/80);
                    B = norm(par.gnss_ant_body(1,:)-par.gnss_ant_body(2,:));
                    sig_att_h = par.sig_carrier*mp / (B*sqrt(ns_k));
                    sig_att_rp = sig_att_h * 3;
                    p_amb = max(0, 1-exp(-0.8*(ns_k-5)));
                    if rand < p_amb
                        gnss_att(k).valid = true;
                        gnss_att(k).z = traj.att(:,k) + [sig_att_h; sig_att_rp; sig_att_rp].*randn(3,1);
                        gnss_att(k).R = diag([sig_att_h^2, sig_att_rp^2, sig_att_rp^2]);
                    end
                end
            end
        end

        if rand<par.pdrop; continue; end
        a=squeeze(plat.aw(:,:,k));
        R_ship=eul2r(traj.att(1,k),traj.att(2,k),traj.att(3,k));
        any_valid=false;
        for ti=1:par.Ntags
            tag_w=(R_ship*par.tags_body(ti,:)'+traj.pos(:,k))';
            rng_all=zeros(M,1);
            for j=1:M; rng_all(j)=norm(tag_w-a(j,:)); end
            if rng_all(ref)>par.uwb_max_rng; continue; end
            zt=[]; vi=[];
            for j=1:M
                if j==ref||rng_all(j)>par.uwb_max_rng; continue; end
                rd=rng_all(j)-rng_all(ref); bias=0;
                if rand<par.pnlos; bias=max(abs(par.sig_nlos*randn)*.8,0); end
                zt=[zt; rd+bias+par.sig_tdoa*randn]; vi=[vi; j];
            end
            if length(zt)>=3
                uwb(k).z_tags{ti}=zt; uwb(k).aidx_tags{ti}=vi; any_valid=true;
            end
        end
        if any_valid; uwb(k).valid=true; uwb(k).apos=a; end
    end
    meas.gnss=gnss; meas.gnss_att=gnss_att; meas.uwb=uwb;
end

function [est, dg] = run_ekf(traj, plat, meas, par, method, comp)
    N=par.N; dt=par.dt; ref=par.ref; nx=12;
    x=zeros(nx,1); x(1:3)=traj.pos(:,1)+5*randn(3,1);
    x(4:6)=traj.vel(:,1)+randn(3,1); x(7:9)=traj.att(:,1)+.1*randn(3,1);
    P=diag([25 25 25 4 4 4 .1 .05 .05 .01 .01 .01]);
    Qp=par.sig_a^2*[dt^4/4*eye(3),dt^3/2*eye(3);dt^3/2*eye(3),dt^2*eye(3)];
    Qa=diag([par.sig_om^2,par.sig_rp^2,par.sig_rp^2])*dt;
    Qw=diag([par.sig_om^2,par.sig_rp^2,par.sig_rp^2])*dt^2*.1;
    Q=blkdiag(Qp,Qa,Qw);
    est.pos=zeros(3,N); est.vel=zeros(3,N); est.att=zeros(3,N);
    est.pos(:,1)=x(1:3); est.vel(:,1)=x(4:6); est.att(:,1)=x(7:9);
    dg.nis=zeros(1,N);

    for k=2:N
        F=eye(nx); F(1:3,4:6)=dt*eye(3); F(7:9,10:12)=dt*eye(3);
        x=F*x; P=F*P*F'+Q; x(7:9)=wrapToPi(x(7:9));

        skip_gnss = any(strcmp(method,{'mtag_only'}));
        if ~skip_gnss && meas.gnss(k).valid
            R_est=eul2r(x(7),x(8),x(9));
            z_pred=R_est*par.gnss_body+x(1:3);
            Hg=zeros(3,nx); Hg(1:3,1:3)=eye(3);
            for ai=1:3; xp=x;xp(6+ai)=xp(6+ai)+1e-5;
                Rp=eul2r(xp(7),xp(8),xp(9));
                Hg(:,6+ai)=(Rp*par.gnss_body+xp(1:3)-z_pred)/1e-5; end
            nu=meas.gnss(k).z-z_pred; Sg=Hg*P*Hg'+meas.gnss(k).R;
            Kg=P*Hg'/Sg; x=x+Kg*nu;
            P=(eye(nx)-Kg*Hg)*P*(eye(nx)-Kg*Hg)'+Kg*meas.gnss(k).R*Kg';
            x(7:9)=wrapToPi(x(7:9));
        end

        use_gnss_att = any(strcmp(method,{'gps_4ant','gpsnav_4ant','mtag_gps','mtag_gpsnav'}));
        if use_gnss_att && isfield(meas,'gnss_att') && meas.gnss_att(k).valid
            Ha=zeros(3,nx); Ha(1,7)=1; Ha(2,8)=1; Ha(3,9)=1;
            nu_a = wrapToPi(meas.gnss_att(k).z - x(7:9));
            Sa=Ha*P*Ha'+meas.gnss_att(k).R;
            Ka=P*Ha'/Sa; x=x+Ka*nu_a;
            P=(eye(nx)-Ka*Ha)*P*(eye(nx)-Ka*Ha)'+Ka*meas.gnss_att(k).R*Ka';
            x(7:9)=wrapToPi(x(7:9));
        end

        do_tdoa = any(strcmp(method,{'mtag_only','mtag_gps','mtag_gpsnav','uwb1tag_gps'}));
        if do_tdoa && meas.uwb(k).valid
            a_all=meas.uwb(k).apos;
            if strcmp(comp,'none'); a_use=par.anch_body+par.plat_pos';
            elseif strcmp(comp,'seastate'); a_use=par.anch_body+par.plat_pos';
                a_use(:,3)=a_use(:,3)+plat.hv(k);
            elseif strcmp(comp,'gnss_plat'); a_use=a_all;
                for jj=1:size(a_use,1); a_use(jj,:)=a_use(jj,:)+0.1*randn(1,3); end
            else; a_use=a_all; end

            R_est=eul2r(x(7),x(8),x(9));
            ntags_use=par.Ntags;
            if strcmp(method,'uwb1tag_gps'); ntags_use=1; end

            all_nu=[]; all_H=[]; all_R=[];
            for ti=1:ntags_use
                zt=meas.uwb(k).z_tags{ti}; if isempty(zt); continue; end
                aidx=meas.uwb(k).aidx_tags{ti}; if isempty(aidx); continue; end
                m=min(length(zt),length(aidx)); zt=zt(1:m); aidx=aidx(1:m);
                tb=par.tags_body(ti,:)'; tw=R_est*tb+x(1:3);
                h=zeros(m,1); J=zeros(m,nx);
                r0=norm(tw-a_use(ref,:)');
                for ii=1:m; j=aidx(ii);
                    rj=norm(tw-a_use(j,:)'); ej=(tw-a_use(j,:)')/max(rj,.01);
                    e0=(tw-a_use(ref,:)')/max(r0,.01);
                    h(ii)=rj-r0; J(ii,1:3)=(ej-e0)';
                    for ai=1:3; xp=x;xp(6+ai)=xp(6+ai)+1e-5;
                        Rp=eul2r(xp(7),xp(8),xp(9)); twp=Rp*tb+xp(1:3);
                        rjp=norm(twp-a_use(j,:)'); r0p=norm(twp-a_use(ref,:)');
                        J(ii,6+ai)=((rjp-r0p)-h(ii))/1e-5; end
                end
                all_nu=[all_nu;zt-h]; all_H=[all_H;J];
                all_R=blkdiag(all_R,par.sig_tdoa^2*eye(m));
            end

            if ~isempty(all_nu)
                is_ad = any(strcmp(method,{'mtag_gpsnav','mtag_gps'}));
                if is_ad; Jp=all_H(:,1:3);
                    if size(Jp,1)>=3; kap=min(cond(Jp'*Jp),par.kappa_max);
                    else; kap=par.kappa_max; end
                    all_R=all_R*(1+par.beta_geo*log(1+(kap-1))); end
                St=all_H*P*all_H'+all_R;
                nis_v=all_nu'/St*all_nu; dg.nis(k)=nis_v;
                if is_ad && nis_v>par.tau_nis; all_R=all_R*par.gamma_nis;
                    St=all_H*P*all_H'+all_R; end
                Kt=P*all_H'/St; x=x+Kt*all_nu;
                P=(eye(nx)-Kt*all_H)*P*(eye(nx)-Kt*all_H)'+Kt*all_R*Kt';
                x(7:9)=wrapToPi(x(7:9));
            end
        end
        est.pos(:,k)=x(1:3); est.vel(:,k)=x(4:6); est.att(:,k)=x(7:9);
    end
end

function [cp, ch, rk] = compute_crlb_6dof(p, att, tags, par)
    M=par.M; ref=par.ref; R_s=eul2r(att(1),att(2),att(3));
    a=par.anch_body+par.plat_pos'; all_J=[];
    for ti=1:size(tags,1); tw=R_s*tags(ti,:)'+p;
        r0=norm(tw-a(ref,:)');
        for j=1:M; if j==ref; continue; end
            rj=norm(tw-a(j,:)'); ej=(tw-a(j,:)')/max(rj,.01);
            e0=(tw-a(ref,:)')/max(r0,.01); row=zeros(1,6); row(1:3)=(ej-e0)';
            for ai=1:3; ap=att;ap(ai)=ap(ai)+1e-5;
                Rp=eul2r(ap(1),ap(2),ap(3)); twp=Rp*tags(ti,:)'+p;
                rjp=norm(twp-a(j,:)'); r0p=norm(twp-a(ref,:)');
                row(3+ai)=((rjp-r0p)-(rj-r0))/1e-5; end
            all_J=[all_J;row]; end; end
    FIM=all_J'*(1/par.sig_tdoa^2*eye(size(all_J,1)))*all_J;
    rk = rank(FIM);
    if rk>=6; C=inv(FIM); cp=sqrt(trace(C(1:3,1:3))); ch=sqrt(C(4,4));
    else; cp=999; ch=999; end
end

function a = wrapTo180(a)
    a = mod(a+180,360)-180;
end